baseurl = "/"
languageCode = "en-us"
theme = "hugo-theme-hello-friend"
paginate = 5

[caches]
  [caches.assets]
    maxAge = "600h"

[languages]
  [languages.en]
    title = "The sound of musq"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "More"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "Jan 2, 2006"
    dateFormatList = "Jan 2, 2006"

    [languages.en.params.logo]
      logoText = "the sound of musq"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "archive"
        name = "Archive"
        url = "/archive"
        weight = 3
